/**
 * Copies `ClearMacroForwarderV1` ABI from a local protocol-monorepo build into this repo.
 *
 * Prerequisite (in protocol-monorepo):
 *   cd packages/ethereum-contracts && yarn build
 *
 * Usage:
 *   PROTOCOL_MONOREPO=../protocol-monorepo pnpm run abi:sync:clear-macro-forwarder
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const protocolRoot = resolve(
  process.env.PROTOCOL_MONOREPO ?? "../protocol-monorepo",
);
const bundledPath = resolve(
  protocolRoot,
  "packages/ethereum-contracts/build/bundled-abi.json",
);
const outPath = resolve("src/chain/clearMacroForwarderV1.abi.ts");

function run(): void {
  const bundled = JSON.parse(readFileSync(bundledPath, "utf8")) as Record<
    string,
    unknown
  >;
  const abi = bundled.ClearMacroForwarderV1;
  if (!Array.isArray(abi)) {
    throw new Error(
      `Missing ClearMacroForwarderV1 in ${bundledPath}. Run ethereum-contracts build first.`,
    );
  }
  const source = [
    "/** AUTO-GENERATED by scripts/sync-clear-macro-forwarder-abi.ts — do not edit. */",
    `export const clearMacroForwarderV1Abi = ${JSON.stringify(abi, null, 2)} as const;`,
    "",
  ].join("\n");
  writeFileSync(outPath, source, "utf8");
  console.log(`Wrote ${outPath} (${abi.length} ABI entries)`);
}

try {
  run();
} catch (error) {
  console.error(error);
  process.exitCode = 1;
}
